name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: "npm-cache"
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache-dependency-path: go.sum
      - name: "make"
        run: |
          git config --global --add safe.directory /github/workspace
          make -O -j fmt lint test
        env:
          COVERALLS_TOKEN: ${{ secrets.github_token }}
      - name: Upload coverage.html
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ci/out/coverage.html
